{{- if and (eq .Values.authentication "htpasswd") (empty .Values.htpasswd.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}-htpasswd-secret
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  htpasswd: {{ (htpasswd .Values.htpasswd.username .Values.htpasswd.password) | b64enc }}
{{- end }}
